- src/dipdup/config.py
Fixes leading underscore bug ParameterTypeMixin.initialize_parameter_cls as detailed in #96
> Fix leading underscore bug

- src/dipdup/config.py
- tests/test_dipdup/test_config/test_custom_config.py
* Dict[str, Any] structure added
* Fixed environment variable substitution pattern
* Unit tests added
> User-defined Custom Config

- CHANGELOG.md
- src/dipdup/dipdup.py
> Fix spawning datasources in oneshot mode

- src/demo_hic_et_nunc/handlers/on_collect.py
- src/demo_hic_et_nunc/handlers/on_swap.py
- src/demo_quipuswap/handlers/on_fa12_divest_liquidity.py
- src/demo_quipuswap/handlers/on_fa12_invest_liquidity.py
- src/demo_quipuswap/handlers/on_fa12_transfer.py
- src/demo_quipuswap/handlers/on_fa12_withdraw_profit.py
- src/demo_quipuswap/handlers/on_fa2_divest_liquidity.py
- src/demo_quipuswap/handlers/on_fa2_invest_liquidity.py
- src/demo_quipuswap/handlers/on_fa2_transfer.py
- src/demo_quipuswap/handlers/on_fa2_withdraw_profit.py
- src/demo_tezos_domains/handlers/on_storage_diff.py
- src/demo_tzbtc/handlers/on_balance_update.py
- src/demo_tzbtc_transfers/handlers/on_balance_update.py
- src/demo_tzcolors/handlers/on_bid.py
- src/demo_tzcolors/handlers/on_withdraw.py
- src/demo_tzcolors/models.py
- src/dipdup/__main__.py
- src/dipdup/config.py
- src/dipdup/datasources/tzkt/datasource.py
- src/dipdup/datasources/tzkt/models.py
- src/dipdup/dipdup.py
- src/dipdup/hasura.py
- src/dipdup/http.py
- src/dipdup/models.py
- src/dipdup/scheduler.py
- src/dipdup/utils/database.py
- tests/integration_tests/test_demos.py
Tortoise ORM FINALLY got full mypy support
> Improve typechecking

- src/dipdup/utils/__init__.py
- tests/integration_tests/test_codegen.py
- tests/integration_tests/test_hasura.py
> Do not skip integration tests in CI

- .github/workflows/docs.yml
> Build docs-next for prereleases

- CHANGELOG.md
- src/dipdup/datasources/subscription.py
- src/dipdup/index.py
> Fix crash when adding an index with new subscriptions in runtime

- README.md
> Remove community survey link

- CHANGELOG.md
- src/dipdup/hasura.py
> Fix processing M2M relations in Hasura

- CHANGELOG.md
- src/dipdup/context.py
> Do not wrap known exceptions with `CallbackError`

- CHANGELOG.md
- src/dipdup/cli.py
- src/dipdup/context.py
- src/dipdup/utils/database.py
> Wrap schema wiping in a transaction to avoid orphaned tables in the immune schema

- CHANGELOG.md
- poetry.lock
- src/demo_tzcolors/handlers/on_bid.py
- src/demo_tzcolors/handlers/on_create_auction.py
- src/demo_tzcolors/models.py
- src/dipdup/utils/database.py
- tests/integration_tests/test_demos.py
> Raise `DatabaseConfigurationError` when backward relation name equals table name

- CHANGELOG.md
- src/dipdup/datasources/tzkt/datasource.py
- src/dipdup/models.py
> Remove deprecated block field `priority`

- .github/workflows/installer.yml
- scripts/install.py
> Install cookiecutter and poetry globally

- CHANGELOG.md
- src/dipdup/config.py
> Configure package logger in addition to `dipdup` one

- CHANGELOG.md
- src/dipdup/models.py
- tests/test_dipdup/test_rollback.py
> Fix crash when using F expressions in versioned transactions

- CHANGELOG.md
- src/dipdup/dipdup.py
> Fix crash when schema generation should fail with `schema_modified`

- CHANGELOG.md
- src/dipdup/cli.py
- src/dipdup/sentry.py
> Flush and reopen Sentry session daily

- CHANGELOG.md
- docs/deployment/docker.md
- src/dipdup/cli.py
Unfortunately, Apache stuff is nearly impossible to build on musl.
> Announce Alpine image deprecation

- CHANGELOG.md
- src/dipdup/config.py
- src/dipdup/yaml.py
> Fix `from_` field alias in token transfer handler

- src/dipdup/__init__.py
- src/dipdup/cli.py
- src/dipdup/exceptions.py
- src/dipdup/project.py
- src/dipdup/yaml.py
Make configuration version check simplier
> (2/2) Introduce spec_version 2.0

- CHANGELOG.md
- src/dipdup/datasources/datasource.py
- src/dipdup/http.py
> Fix crash when using custom datasources

- README.md
all-contributors bot is too bulky. Whaddya think; are plain lists enough to begin with?
> Add sponsors and contributors to README.md

- CHANGELOG.md
- README.md
- src/dipdup/http.py
> Retry aiohttp requests on asyncio.TimeoutError

- src/dipdup/config/__init__.py
> Make advanced config accept any options

- CHANGELOG.md
- src/dipdup/context.py
- src/dipdup/dipdup.py
- src/dipdup/scheduler.py
> Fix jos scheduler delayed start

- CHANGELOG.md
- docs/15.thanks.md
- src/dipdup/datasources/evm_node.py
- src/dipdup/dipdup.py
- src/dipdup/indexes/evm_subsquid_events/index.py
- src/dipdup/models/evm_node.py
- src/dipdup/models/evm_subsquid.py
> Fix parsing topics and integers in evm.mode models

- CHANGELOG.md
- src/dipdup/install.py
fix error with all meaningful answers interpreted as yes in some cases
> Ask function in install script fix

- CHANGELOG.md
- src/demo_uniswap/models/__init__.py
- src/dipdup/cli.py
- src/dipdup/indexes/evm_subsquid_events/index.py
- src/dipdup/projects/demo_uniswap/models/__init__.py.j2
> Fixed node log request, decimals in uniswap demo

- CHANGELOG.md
- src/dipdup/hasura.py
> Increase initial Hasura connection retry count

- CHANGELOG.md
- docs/15.thanks.md
- src/dipdup/cli.py
> Fix crash on early Python 3.11 releases

- docs/6.deployment/4.prometheus.md
- docs/7.references/2.config.md
- src/dipdup/config/__init__.py
- src/dipdup/config/evm_subsquid_events.py
- src/dipdup/context.py
- src/dipdup/dipdup.py
- src/dipdup/http.py
- src/dipdup/index.py
- src/dipdup/indexes/evm_subsquid_events/index.py
- src/dipdup/indexes/tezos_tzkt.py
- src/dipdup/indexes/tezos_tzkt_big_maps/index.py
- src/dipdup/indexes/tezos_tzkt_events/index.py
- src/dipdup/indexes/tezos_tzkt_operations/index.py
- src/dipdup/indexes/tezos_tzkt_token_transfers/index.py
- src/dipdup/performance.py
- src/dipdup/prometheus.py
Removed metrics level, cleared code
> Refactor metrics

- CHANGELOG.md
- src/dipdup/codegen/evm_subsquid.py
- src/dipdup/config/__init__.py
- src/dipdup/datasources/evm_node.py
- src/dipdup/indexes/evm_subsquid_events/index.py
* Significantly reduced number of requests
* Unused block details excluded from response
> EvmNodeDatasource._synchronize() optimisations

- src/dipdup/hasura.py
* replaced set of single `pg_set_table_customization` requests with a bulk one.
* became possible to use `bulk` request `type` in custom metadata files `./hasura/*.json`.
> Allow bulk requests in Hasura Metadata API
